title: Default File

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Caption
            type: textarea
            size: medium
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternative Text
            type: text
          imageTitle:
            label: Image Title
            type: text
          photographer:
            label: Photographer
            type: text
            width: 2/3
          license:
            label: License
            type: select
            width: 1/3
            options:
              - Unsplash
              - CC BY 4.0
              - CC BY-SA 4.0
              - CC BY-SA 2.0
              - CC BY-NC-SA 2.0
              - CC BY-NC 4.0
              - CC BY-NC 2.0
              - CC BY-ND 4.0
              - CC0 1.0
          licenseUrl:
            label: License URL
            type: text
          link:
            label: Link
            type: url

