<?php snippet('header') ?>
<?php snippet('platform-menu') ?>
<?php snippet('breadcrumb') ?>
<?php snippet('show-status') ?>
<?php snippet('open-platform-content') ?>
<?php snippet('show-blocks') ?>
<?php snippet('check-access') ?>
<?php snippet('tasks/measure') ?>
<?php snippet('close-platform-content') ?>
<?php snippet('footer') ?>
