title: NatEnt Platform

columns:
  - width: 2/3
    sections:
      info:
        type: info
        label: info
        text: |
          Welcome to the NatEnt Platform content management system.
          Add and edit Pages from the panel below.

          All the phase content is in the Learning Journey section.

          
      pages:
        label: Pages
        type: pages
        templates:
          - home
          - about
          - for-teachers
          - for-students
          - platform-home
          - contact
          - register
          - error
  - width: 1/3
    sections:
      settings:
        label: Settings
        type: pages
        templates:
          - areas
          - challenges
      phases:
        label: Phase Types
        type: pages
        templates:
          - phase

